# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    build: .
    # uncomment these if you are having this issue with the build:
    # /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:509:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/.gitignore (Errno::EACCES)
    # and fill the args values with the output of the commands on the right
    # build:
    #   args:
    #     GROUPID: # id -g
    #     GROUPNAME: # id -gn
    #     USERID: # id -u
    #     USERNAME: # echo $USER
    ports:
      - 8080:8080
      - 35729:35729 # 35729 是 LiveReload 的默认端口，确保也暴露出来
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    develop:
      watch:
        - action: sync
          path: ./               # 本地代码根目录
          target: /srv/jekyll    # 容器中代码路径
          ignore:
            - _site/             # Jekyll 生成的文件夹忽略
            - node_modules/
        - action: rebuild
          path: Gemfile